version: '3.1'
services:
  db:
    container_name: magento-db
    image: mysql
    # volumes:
    #   - ./database/backup:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_USER: 'magento'
      MYSQL_PASSWORD: 'magento'
      MYSQL_DATABASE: 'magento'
    ports: 
      - "3306:3306"
    tty: true
    restart: always
  web:
    container_name: magento-web
    build: 
      context: ./docker/
    image: magento-web:latest
    ports:
    - 80:80
    volumes:
    - .:/var/www
    environment:
    - DB_HOST=magento-db
    extra_hosts:
    - "localhost:127.0.0.1"
    entrypoint: [ "/bin/sh" , "./docker/entrypoint.sh" ]
    command: php -S 0.0.0.0:80
    depends_on:
      - db
    links:
      - db
    tty: true
    restart: always
    
  # front:
  #   container_name: sys-front
  #   build: 
  #     context: ./docker/front/
  #   image: sys-front:latest
  #   volumes:
  #   - .:/var/www
  #   entrypoint: [ "/bin/sh" , "./docker/front/entrypoint.sh" ]
  #   command: yarn watch
  #   depends_on:
  #     - web
  #   tty: true
  #   restart: always

# volumes:
#   "./database:/var/lib/mysql"

  # volumes:
    # ./database:/var/lib/mysql
# volumes:
#   mysql-db: